### ISSUE TITLE
Duplication and balance

### ISSUE THREAD

**Issue by miyucomics** [Jempasam/Hexlink#1]
Currently, it is possible to duplicate blocks and entities endlessly, including boss mobs. I don't think this is intended. For example, by getting the spirit of an ender dragon, you can summon endless Ender Dragons at will. There is also block duplication. If you get the spirit of an diamond block, you can manifest diamond blocks forever and clone the original.

**Comment by Jempasam** [comment]
Great Focus are not rewritables and empty Great Focus are rare loots. You can change the mod loot table to totally remove the possibility of finding empty Great Focus.
I want that unlocking the possibility of summoning is hard, but after you did, you have no limitation.
However I'll try to balance Spirit Extraction somewhat.
Thanks for your feedback, I'll try my best to make the mod more balanced and interesting for survival.
