### ISSUE TITLE
Hexlink Spirit Transfer Multiplayer Disconnect

### ISSUE THREAD

**Issue by lakehascake** [Jempasam/Hexlink#12]
**Describe the bug**
When using HexLink on a multiplayer server and trying to put spirits into containers, the **clients who are near the edited items** gets disconnected.

**To Reproduce**
Steps to reproduce the disconnect:
1. Go on a Minecraft server with HexLink
2. Use any form of spell that **transfers spirits** (examples that are confirmed to work: Spirit Extraction, Spirit Manifestation)
3. Get error "*io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(80) + length(8) exceeds writerIndex(85): PooledUnsafeDirectByteBuf(ridx: 80, widx: 85, cap: 85)*"

**Expected behavior**
The player should not be disconnected when changing anything with spirits, multiplayer or singleplayer.

**Screenshots**
![image](https://github.com/Jempasam/Hexlink/assets/155930890/fe0dc068-c6b3-4ac7-a98a-38eb2e9ec816)

**Client Information:**
 - OS: Windows 11
 - Minecraft Version: 1.19.2
 - Mod Version: 2.2.7
 - Note: Mods list is too big to send all at once, refer to 2nd point under Additional Content.

**Additional context**
- Leading theory of the problem could be a lack of testing on multiplayer worlds, evidence of researching the error backs up this claim.
- I am willing to provide a file of the modpack zip for testing purposes.

**Comment by Jempasam** [comment]
Ok this is because of particles, I corrected it, i'll publish a new version after some more bug corrections.

**Comment by Jempasam** [comment]
In release 2.2.9
