### ISSUE TITLE
Tutorial for Special Staff

### ISSUE THREAD

**Issue by AlexChecker** [Jempasam/Hexlink#14]
So there is this Special Staff item. It's cool but it's not so clear how to program it properly

**Describe the solution you'd like**
Section in wiki dedicated to explanation of Special Staff usage

**Describe alternatives you've considered**
Maybe hexdoc for all spells/crafts/tutorials

**Additional context**

**Comment by Jempasam** [comment]
Ok, i'll try to make an hexdoc.

**Comment by Jempasam** [comment]
I don't know how hexdoc works.
I wrote a page on the github wiki: https://github.com/Jempasam/Hexlink/wiki/2)-The-Special-Staff
