### ISSUE TITLE
Enchantment Duping

### ISSUE THREAD

**Issue by Archmage-Erebus** [Jempasam/Hexlink#17]
When you enchant an item with a spirit, only one spirit is deducted regardless of the enchantment level. However, extracting enchantments still give back a proportionate amount of enchant spirits, so you can just print infinite copies of the same enchant over and over

**Comment by Jempasam** [comment]
Oh thank you, I will change it and make some more tweak.

**Comment by Jempasam** [comment]
It's  done and uploaded on modrinth
