### ISSUE TITLE
howdy

### ISSUE THREAD

**Issue by SamsTheNerd** [Jempasam/Hexlink#3]
hey, didn't know if there was a better way to contact you. your mod has been getting a good bit of attention in the hexcasting discord server, not sure if you're in there but if not here's a link if you'd like to join https://discord.gg/4xxHGYteWk !

other thing i wanted to ask is if it's ok for me to put a link to this in https://hexxy.media/addons ?

**Comment by Jempasam** [comment]
Yes, you can, thank you
